# Generated by Django 5.2.4 on 2025-07-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
